version: "3"
services:
  identities-graph:
    build: identities-graph/
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  payments-graph:
    build: payments-graph/
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
  gateway:
    build: gateway/
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - SLEEP=9
      - SERVICE_LIST=[{"name":"identities-graph","url":"http://identities-graph:8080/graphql"},{"name":"payments-graph","url":"http://payments-graph:8081/graphql"}]
    depends_on:
      - "identities-graph"
      - "payments-graph"
